### ISSUE TITLE
'HighFive' headers not found by cmake target link libraries

### ISSUE THREAD

**Issue by KevinCain** [raphaelsulzer/mesh-tools#1]
By chance have you seen linking errors with the `HighFive` dependencies for `mesh-tools`?

I can complete cmake configuring, but then get the cmake error I show below. As I understand it, `HighFive` is a header-only library, so I don't see why the linker needs to know anything about it.

I haven't located where 'HighFive_libheaders' is being added to the cmake target link libraries via the variables in `CMakeLists.txt`.

I can have a deeper look, but wanted first to see if this happens to be a known trouble point.

Here's the error:

```
-- Configuring done
CMake Error at CMakeLists.txt:548 (target_link_libraries):
Error evaluating generator expression:

$<TARGET_PROPERTY:HighFive_libheaders,INTERFACE_INCLUDE_DIRECTORIES>

Target "HighFive_libheaders" not found.
```

**Comment by raphaelsulzer** [comment]
Hi,
It is probably a dependency of xtensor, which is required by mesh-tools for reading and writing npz files. You can try to install it with `sudo apt-get install libhdf5-dev`.

**Comment by KevinCain** [comment]
I'm a bit stumped by this -- I can't find where 'HighFive_libheaders' is referenced by cmake.

I'm on Arch, which does not use the familiar `-dev` package convention in Ubuntu. The Arch library equivalent is simply 'hdf5' in this case, which I already have installed along with the following `mesh-tools` dependencies:

**Xtensor AUR:**
https://aur.archlinux.org/xtensor.git
Xtensor dependencies as per https://aur.archlinux.org/packages/xtensor :
     **XTL AUR:**
```
     git clone https://aur.archlinux.org/packages/xtl
     cd xtl
     makepkg -sri
     (sudo pacman -U <package_name>.tar.xz / .tar.zst)
```
	
**Xtensor-io AUR:**
https://aur.archlinux.org/packages/xtensor-io 

**High Five AUR:**
https://aur.archlinux.org/highfive.git

**hd5ff** (also tried: hd5f-openmpi)
https://archlinux.org/packages/community/x86_64/hdf5-openmpi/ 

**CGAL-git** (v 5.1.1+ required):
https://aur.archlinux.org/packages/cgal-git 

**Open3D AUR:**
https://aur.archlinux.org/open3d.git

**Comment by raphaelsulzer** [comment]
I am not using hdf5 in mesh-tools.

The only idea I would have is to make sure that the xtensor stack was able to find hdf5 during installation.

Maybe I can try to build mesh-tools in a docker with Arch some time, but it will take a while.

**Comment by KevinCain** [comment]
I was able to build `feat` with `OMVS_ENABLED` after a few minor tweaks (see below), however invoking with OMVS input returns with complaints of an unrecognized input format:
`ERROR: not a valid reconstruction input`

As above, to compile I needed to make a few minor changes tracing mismatches between deprecated and non-deprecated calls to CGAL helper routines, likely from clashing dependencies in different libraries (`OMVS` v `mesh-tools`):

- In “/usr/include/CGAL/Surface_mesh/IO/PLY.h:1136” I explicitly prepend the `CGAL::IO::` namespace before ‘write_PLY’
- In “/home/kevin/mesh-tools/src/IO/fileIO.cpp:327” I added a ‘comments’ string to the ‘read_ply’ call in order to match caller and function, i.e.:

```
    std::string text = "";
    std::string& comments = text;
    read_ply(in,import_mesh,comments);

```

**Comment by raphaelsulzer** [comment]
OK, thanks for sharing this!

I am not sure why you are getting the error. As you can see in [this line](https://github.com/raphaelsulzer/mesh-tools/blob/b11d5bbca207387961c8c8b36b16fffd5e3f364b/src/exe/feat.cpp#L82), once you have build feat with OMVS_ENABLED you should be able to read omvs projects when you call feat with `-s omvs`.

Also be aware that the omvs project path currently is hardcoded to be `$workingDir/openMVS/densify_file.mvs` [in this line](https://github.com/raphaelsulzer/mesh-tools/blob/b11d5bbca207387961c8c8b36b16fffd5e3f364b/src/IO/fileIO.cpp#L508). However, this does not explain your error.

**Comment by KevinCain** [comment]
Thanks for the clarification; on your Ubuntu build did you build `openMVS` with `-DBUILD_SHARED_LIBS=ON`? On Garuda/Arch I have compiled both as a shared library and not, with no impact on building `mesh-tools`.

I believe my problem comes from an `openMVS` header that CMake isn't generating, [which I've asked about in an openMVS issue](https://github.com/cdcseacave/openMVS/issues/768).

Back to `mesh-tools`, the `CMakeList.txt` library linking order seems sensitive; to compile `mesh-tools` without errors I found I had to cut `xtensor-io` and shuffle `xtensor` upwards in the block at CMakeLists.txt:518:
```
   target_link_libraries(feat
                        fileIO
                        learning
                        rPLY
                        util
                        processing
                        xtensor
                        ${OCV_EXTERNAL_LIBRARIES}
                        ${OMVS_EXTERNAL_LIBRARIES} # this has to be written before OpenMP for some reason
                        ${RECONBENCH_EXTERNAL_LIBRARIES}
                        ${PCL_EXTERNAL_LIBRARIES}
                        ${Boost_LIBRARIES}
                        ${GLOG_LIBRARIES}
                        ${CERES_LIBRARIES}
                        ${GMP_LIBRARY}
                        ${MPFR_LIBRARY}
                        ${Open3D_LIBRARIES}
                        CGAL::CGAL
                        OpenMP::OpenMP_CXX
                        ZLIB::ZLIB
                        )
```

**Comment by KevinCain** [comment]
I'll assume we need to compile `openMVS` with `-DBUILD_SHARED_LIBS=ON`. There appear to be known problems with `openMVS` and [recent versions of OpenCV](https://github.com/cdcseacave/openMVS/issues/364) in this state.

From a clean repo with the above changes, make finds the `openMVS` libraries but some symbols are still unresolved:

```
/usr/bin/ld: libfileIO.a(fileIO.cpp.o): undefined reference to symbol '_ZN7SEACAVE9ColorTypeIfE3ONEE'
/usr/bin/ld: /home/kevin/openMVS_build/lib/libCommon.so: error adding symbols:DSO missing from command line
```

**Comment by raphaelsulzer** [comment]
I personally also have problems with compiling OpenMVS with some of its applications. However, the core module - which is the only thing necessary for mesh-tools - compiles fine with shared libraries on or off.

The important thing is that if you compile mesh-tools with `-DSTATIC=ON` you need OpenMVS to be compiled with `-DBUILD_SHARED_LIBS=OFF` and all other libraries also need to be linked statically. 
If you compile mesh-tools with `-DSTATIC=OFF` you need OpenMVS to be compiled with `-DBUILD_SHARED_LIBS=ON` and all other libraries also need to be linked dynamically.

**Comment by KevinCain** [comment]
Thanks @raphaelsulzer for your explicit notes, which make good sense. I've tried both ways you outline. I find on Arch that I can compile+link `openMVS` fully with  `-DBUILD_SHARED_LIBS=OFF`, but run into problems linking the interface with `-DBUILD_SHARED_LIBS=ON`.

I started with your preferred configuration (`-DBUILD_SHARED_LIBS=OFF`) as noted in my earlier posts, and in this case I see the statically linked libraries generated in `/openMVS_build/lib` that we'd expect, as follows:

- ibCommon.a
- libIO.a
- libMath.a
- libMVS.a

When invoking CMake for `mesh-tools`, I'm using:
`cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DSTATIC=ON`

I'm using OpenMP 13.x & OpenCV 4.5.x as reported via:
```
pacman -Q --info opencv
Name            : opencv
Version         : 4.5.5-3
pacman -Q --info openmp
Name            : openmp
Version         : 13.0.1-1
```

**Comment by KevinCain** [comment]
In the hope that it's useful to others building `mesh-tools`, below are some of the key points I've encountered trying to compile static libraries for the needed dependencies.

This process includes statically compiling `openCV` and its dependencies, which is fair amount of work in itself since the `-DBUILD_SHARED_LIBS=OFF` CMake flag is only the beginning of several other independent switches for compiling its modules statically. See below for details.

These notes are for an Arch distro, so your mileage may vary.

**OpenMP static (via custom server)**
sudo pacman -Syu openmp-static
https://archlinux.pkgs.org/rolling/jlk-x86_64/openmp-static-12.0.1-1-x86_64.pkg.tar.zst.html
	Set up [the [jlk] repo key](https://jlk.fjfi.cvut.cz/arch/repo/README.html)

**OpenCV static on [Arch](https://techesoterica.com/installing-opencv-on-arch-linux-from-source/)**
We turn ffmpeg off as [ffmpeg 5 causes problems](https://github.com/opencv/opencv/issues/20147) but is required on the system elsewhere
git clone https://github.com/opencv/opencv.git

NOTE: `/usr/local/lib/cmake/opencv4/OpenCVConfig.cmake` hard codes `SHARED ON`. To build static libraries:
  `set(OpenCV_SHARED OFF)`

```
cmake -DBUILD_SHARED_LIBS=OFF \
-D WITH_FFMPEG=OFF \
-D CMAKE_BUILD_TYPE=RELEASE \
-D CMAKE_INSTALL_PREFIX=/usr/local \
-D ENABLE_NEON=OFF \
-D ENABLE_VFPV3=OFF \
-D BUILD_TESTS=OFF \
-D INSTALL_PYTHON_EXAMPLES=OFF \
-D OPENCV_ENABLE_NONFREE=OFF \
-D CMAKE_SIZEOF_VOID_P=4 \
-D BUILD_opencv_python3=OFF \
-D BUILD_EXAMPLES=OFF ..

make -j8
sudo make install
```

**GMP static library (arbitrary precision math):**
https://aur.archlinux.org/libgmp-static.git

**MPFR_LIBRARIES**
```
git clone https://gitlab.inria.fr/mpfr/mpfr
cd /mpfr
bash autogen.sh
./configure --disable-shared
make
make check
sudo make install
```

**Comment by raphaelsulzer** [comment]
Thank you very much for these tips!
Can you build mesh-tools with OpenMVS enabled now?

**Comment by KevinCain** [comment]
Arch [”just generally does not package static libraries](https://bbs.archlinux.org/viewtopic.php?id=245303)”, so it's been an intensely manual process and I still have a few unresolved base dependencies to deal with. I'll open a fresh issue once I get a chance to run tests on my data. Thanks once again!
